// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpttmxdrcsmditurlwze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwdHRteGRyY3NtZGl0dXJsd3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5Njk1ODYsImV4cCI6MjA1NTU0NTU4Nn0.6lEBObi1shkBYGuW0sF2xDXtOXYqVDKi8VaM2gNGvQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);